config/routes.rb
Rails.application.routes.draw do
  resources :users, except: [:index]
  resource :sessions, only: [:new, :create, :destroy]
  resources :pages, only: [:index, :about, :landing]
  resource :dashboard, only: [:index]

  namespace :api,
   defaults: { format: :json } do
    resources :boards do
      resources :hooks, only: [:create, :update, :destroy]
    end
    resources :lists, only: [:index, :show, :create, :update, :destroy]
    resources :cards, only: [:index, :create, :update, :destroy, :show]
    resources :repositories, only: [:index, :show]
    resources :issues, only: [:destroy, :show, :create, :update, :index]

  end

  get "/auth/:provider/callback" => "sessions#create"
  get "/landing" => "pages#landing"
  get "/signout" => "sessions#destroy", :as => :signout
  root 'pages#index'

end

app/views/layouts/_errors.html.erb
<%= flash[:errors].join("<br>").html_safe if flash[:errors] %>

app/views/layouts/_footer.html.erb
<div id="footer">
  <footer>
    <ul class="nav navbar-nav navbar-right">
      <li class="nav-li btn btn-primary btn-sm"><%= link_to "Homepage", root_url %></li>
    <%#= link_to "About", about_page_url %>
    </ul>
  </footer>
</div>

app/views/layouts/_header.html.erb
<header>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="/#"><h1 id='catpus-icon'><%= image_tag "tentacle.png", class: "head-ico" %>  Tentacle</h1></a>
        </div>

          <ul class="nav navbar-nav navbar-right">
            <% if logged_in? %>
              <li class="nav-li" id="user-name-img"><img class='thumbnail-header' src="<%= current_user.avatar_url %>"><span id='username'><%= current_user.name %></span></li>
              <li class="nav-li"> <%= link_to "Dashboard", ('/#dashboard') %> </li>
              <li class="nav-li"> <%= button_to "Sign Out", sessions_url, method: :delete %> </li>
            <% else %>
              <a class="btn btn-social-icon btn-github" href="/auth/github/">
                <i class="fa fa-github"></i>
              </a>
            <% end %>
          </ul>
      </div>
    </nav>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
  <title>Tentacle</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render partial: "layouts/header" %>
  <%= yield %>
  <%= render partial: "layouts/footer" %>
</body>
</html>